# Generated by Django 4.2.3 on 2023-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music_type',
            field=models.CharField(blank=True, choices=[('RO', 'Rock'), ('HR', 'Hard Rock'), ('HM', 'Heavy Metal'), ('PO', 'Pop'), ('DA', 'Dance'), ('PU', 'Punk'), ('GR', 'Grunge'), ('FO', 'Folk'), ('IT', 'Italiani')], default='HR', max_length=300, null=True),
        ),
    ]
