# Generated by Django 4.2.3 on 2023-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_music_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
