# Generated by Django 4.2.3 on 2023-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music_type',
            field=models.CharField(blank=True, choices=[('BA', 'da ballare'), ('CA', 'da cantare'), ('RO', 'romantiche'), ('MO', 'dal mondo'), ('LU', 'per lui'), ('LE', 'per lei'), ('OR', 'on the road')], default='CA', max_length=300, null=True),
        ),
    ]
